### ISSUE TITLE
CD (Uploading to Sonatype) deploy action is broken

### ISSUE THREAD

**Issue by terahidro2003** [Mercateo/sqs-utils#27]
Tried to deploy sqs-utils versions [1.0.0] and [1.0.1] (both almost identical) but the Github action in `deploy.yml` failed [1]. The error was `"status: 401 Content access is protected by token"`. Upon some quick research, it turns out that Sonatype changed their preferred authentication method from password-based to a token-based authentication [1]. As a result of this, `Deploy` action fails to upload snapshot versions to Sonatype.

Sources:
[1] 
![image](https://github.com/user-attachments/assets/422db560-91da-479d-a870-8dbd17433e23)
[2] [Sonatype deprecates publishing with username and password](https://central.sonatype.org/news/20240617_migration_of_accounts/#publishing-with-username-password)

**Comment by m-kn** [comment]
Closed because we're archiving this repo
